name: Our CI

on:
  pull_request:
  push:
    - main
    - other-branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python package
        run: python -m pip install .[test]
      - name: Run tests
        run: pyton -m pytest